# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "comments", :force => true do |t|
    t.column "body",     :text
    t.column "entry_id", :integer
  end

  create_table "discussions", :force => true do |t|
    t.column "title",      :string
    t.column "body",       :text
    t.column "created_at", :datetime
    t.column "user_id",    :integer
    t.column "group_id",   :integer
  end

  create_table "entries", :force => true do |t|
    t.column "title",      :string
    t.column "notes",      :text
    t.column "breakfast",  :text
    t.column "lunch",      :text
    t.column "dinner",     :text
    t.column "snacks",     :text
    t.column "workouts",   :text
    t.column "created_on", :date
    t.column "user_id",    :integer
  end

  create_table "groups", :force => true do |t|
    t.column "name",        :string
    t.column "description", :text
  end

  create_table "journals", :force => true do |t|
    t.column "title",      :string
    t.column "notes",      :text
    t.column "workout",    :text
    t.column "breakfast",  :text
    t.column "lunch",      :text
    t.column "dinner",     :text
    t.column "snacks",     :text
    t.column "created_on", :date
  end

  create_table "memberships", :force => true do |t|
    t.column "user_id",  :integer
    t.column "group_id", :integer
  end

  create_table "users", :force => true do |t|
    t.column "name", :string
  end

end
